paths:
  data_path: "data/inputs/heart_cleveland_upload.csv"
  load_model_path: "data/models/SVC_1.0_rbf.pkl"
  save_model_path: "data/models/"
  save_report_path: "data/models/reports/"
  save_preds_path: "data/outputs/predictions/"

data_params:
  target: "condition"
  exclude: "thalach"

sampling_params:
  stratify: True
  test_size: 0.2
  random_state_sampl: 228

prepr_params:
  preprocessing: "StandardScaler"
  random_state_prep: 228


model_params:
  model: "SVC" #possible values: "SVC", "LogisticRegression", "RandomForestClassifier"
  random_state_model: 228
  kernel: "rbf" #only for SVM
  penalty: 'l2'
  n_estimators: 100
  max_depth: 5
